version: '3.1'

services:
  php:
    image: php:7.4-apache
    volumes:
      - ~/CodeExperiments/ds-astro/dist:/var/www/html/
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ds-astro.rule=Host(`ds-astro.test`)"

networks:
  proxy:
    external: true