debug: true

log:
  level: DEBUG

api:
  insecure: true
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entrypoint:
    #       to: web-secure
    #       scheme: https
  web-secure:
    address: ":443"
  # mariadb:
  #   address: ":3306"

providers:
  docker:
    # defaultRule: "Host(`{{ .Name | splitList `-` | reverse | join `.` }}.test`)"
    network: proxy
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true
