version: "3"
 
services:
  portainer:
    image: portainer/portainer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/data/portainer:/data    
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.test`)"
    command: -H unix:///var/run/docker.sock
 
networks:
  proxy:
    external: true